import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

import xarray as xr

import re

from types import TracebackType
from typing import Type

import analysis_functions.core as af
from collections import defaultdict

class cavity_analysis:
    """
    Analysis tools for experimentally measured cavity modes.

    This class provides methods for fitting resonant modes identified
    from cavity simulations, extracting fit parameters from experimental
    data, performing simple linear regressions on mode trajectories, and
    visualizing the resulting mode characteristics.

    Parameters
    ----------
    data : xarray.Dataset
        Experimental dataset containing at least the coordinates
        ``length`` and ``freq`` as well as the complex response data
        used for fitting.
    radius : float
        Cavity radius in millimeters.

    Attributes
    ----------
    data : xarray.Dataset
        Experimental dataset.
    radius : float
        Cavity radius in millimeters.
    model : ComplexCircle
        Resonator model used for fitting individual resonances.
    dict_fits : dict
        Dictionary containing fit results for each fitted resonance.
    dict_results : dict
        Dictionary containing extracted fit parameters grouped by mode.
    dict_polynoms : dict
        Dictionary containing linear polynomial coefficients for each
        fitted mode.
    mask_xr : xarray.DataArray
        Boolean mask identifying data regions used during fitting.
    """

    def __init__(self,
                 data,
                 radius: float):
        """
        Initialize the cavity analysis object.

        Parameters
        ----------
        data : xarray.Dataset
            Experimental dataset containing cavity measurements.
        radius : float
            Cavity radius in millimeters.
        """
        
        self.data = data
        self.radius = radius
        self.model = af.ComplexCircle()
    
    def __enter__(self
                  ) -> "cavity_analysis":
        """
        Enter the context manager.

        Returns
        -------
        cavity_analysis
            Current instance of the class.
        """

        return self
    
    def __exit__(self,
                 exc_type: Type[BaseException],
                 exc_val: BaseException,
                 exc_tb: TracebackType
                 ) -> bool:
        """
        Exit the context manager.

        Parameters
        ----------
        exc_type : Type[BaseException]
            Type of the exception raised within the context block.
        exc_val : BaseException
            Exception instance.
        exc_tb : TracebackType
            Traceback information associated with the exception.

        Returns
        -------
        bool
            Always returns `False` so that exceptions are propagated.
        """
                 
        return False
    
    def __repr__(self
                 ) -> str:
        """
        Return a string representation of the object.

        Returns
        -------
        str
            String describing the main cavity parameters.
        """

        return (f"cavity_analysis(radius={self.radius} mm,\n data: {self.data})")
    
    def fit_branches(self,
                    bandwidth: float,
                    dict_modes: dict,
                    mode_ids: np.ndarray = None):
        """
        Fit cavity resonances along theoretical mode branches.

        For each mode branch, a frequency window centered on the theoretical
        resonance frequency is extracted and fitted using the selected
        resonator model. Fit results are stored in ``dict_fits`` and the
        corresponding data points are recorded in a fitting mask.

        Parameters
        ----------
        bandwidth : float
            Frequency window width in GHz used around each theoretical
            resonance.
        dict_modes : dict
            Dictionary of theoretical cavity modes, typically generated by
            ``cavity_theory.compute_modes()``.
        mode_ids : array-like, optional
            List of mode identifiers to fit. If not provided, all TE modes
            contained in ``dict_modes`` are fitted.

        Notes
        -----
        Fit failures are caught and reported without interrupting the
        processing of the remaining modes.

        Results
        -------
        dict_fits : dict
            Dictionary containing fit objects indexed by
            ``"<mode_id>|<length>"``.
        mask_xr : xarray.DataArray
            Boolean mask identifying all frequency points used during
            fitting.
        """
        
        freqs = self.data.freq.values
        lengths = self.data.length.values

        self.dict_fits = {}
        mask_np = np.zeros((len(lengths), len(freqs)), dtype=bool)

        if mode_ids is None:
            # Fit all TE modes
            for mode_id, branche in dict_modes.items():
                match = re.match(r'^(T[ME])(\d)(\d)(\d)$', mode_id)
                if match:
                    mode_type = match.group(1)

                if mode_type == 'TE':
                    for (length, f0) in branche:
                        fmin, fmax = f0 - bandwidth, f0 + bandwidth
                        data_fit = self.data.sel(length=length, freq=slice(fmin, fmax))

                        try:
                            fit_result = af.fit_single(self.model,
                                                       data_fit.freq.values,
                                                       data_fit.cpx.values,
                                                       guess = None)
                            self.dict_fits[f"{mode_id}|{length}"] = fit_result

                            lidx = np.where(lengths==length)[0][0]
                            fidx = np.isin(freqs, data_fit.freq.values)
                            mask_np[lidx, fidx] = True
                        except Exception as e:
                            print(f"[{mode_id} | {length:.3f} mm | {f0:.3f} GHz] Fit Error: {e}")
        else:
            for mode_id in mode_ids:
                # Fit given TE modes
                branche = dict_modes[mode_id]
                for (length, f0) in branche:
                    fmin, fmax = f0 - bandwidth/2, f0 + bandwidth/2
                    data_fit = self.data.sel(length = length,
                                             freq = slice(fmin, fmax))
                    
                    try:
                        fit_result = af.fit_single(self.model,
                                                    data_fit.freq.values,
                                                    data_fit.cpx.values,
                                                    guess = None)
                        self.dict_fits[f"{mode_id}|{length}"] = fit_result

                        lidx = np.where(lengths==length)[0][0]
                        fidx = np.isin(freqs, data_fit.freq.values)
                        mask_np[lidx, fidx] = True
                    except Exception as e:
                        print(f"[{mode_id} | {length:.3f} mm | {f0:.3f} GHz] Fit Error: {e}")
        
        self.mask_xr = xr.DataArray(mask_np,
                                    coords = {'length': self.data.length, 'freq': self.data.freq},
                                    dims = ['length', 'freq'])
    
    def plot_masked_branches(self, ax=None, **kwargs):
        """
        Display the experimental data restricted to fitted regions.

        The method applies the fitting mask generated by ``fit_branches()``
        and plots only the portions of the dataset that were included in the
        fitting procedure.

        Notes
        -----
        Plot limits are automatically adjusted to the extent of the selected
        data.
        """
        if ax is None:
            fig, ax = plt.subplots()
        
        data_masked = self.data.mag.where(self.mask_xr)

        data_masked.plot(ax = ax, cmap = 'RdBu_r',
                              add_colorbar = True)
        
        valid_freq = self.mask_xr.any(dim='length')
        valid_length = self.mask_xr.any(dim='freq')

        freqs = self.data.freq.values[valid_freq.values]
        lengths = self.data.length.values[valid_length.values]

        ax.set_xlim(lengths.min(), lengths.max())
        ax.set_ylim(freqs.min(), freqs.max())

    def compute_fit_results(self):
        """
        Extract fitted parameters and organize them by mode.

        Parameters obtained from each fit object are collected and grouped
        according to their mode identifier. The resulting structure is stored
        in ``dict_results``.

        Results
        -------
        dict_results : dict
            Nested dictionary whose first-level keys correspond to mode
            identifiers and whose second-level keys correspond to fitted
            parameter names.
        """

        self.dict_results = defaultdict(lambda: defaultdict(list))

        for key, fit in self.dict_fits.items():
            mode_id, length = key.split("|")

            fit_values = {}
            fit_values['length'] = float(length)

            for name in fit.params.keys():
                fit_values[name] = fit.params[name].value
            
            for name, value in fit_values.items():
                self.dict_results[mode_id][name].append(value)
    
    def linear_fit_modes(self,
                         mode_ids: list = None):
        """
        Perform linear fits of resonance frequency versus cavity length.

        A first-order polynomial is fitted to the frequency evolution of
        each selected mode.

        Parameters
        ----------
        mode_ids : list, optional
            List of mode identifiers to fit. If not provided, all available
            modes contained in ``dict_results`` are processed.

        Results
        -------
        dict_polynoms : dict
            Dictionary containing the polynomial coefficients returned by
            ``numpy.polyfit`` for each mode.

        Notes
        -----
        The fitted model is

        .. math::

            f(L) = aL + b

        where ``a`` and ``b`` are the coefficients stored in
        ``dict_polynoms``.
        """
        
        self.dict_polynoms = {}
        
        if mode_ids is None:
            for mode_id, fit_results in self.dict_results.items():
                lengths = fit_results['length']
                frequencies = fit_results['f0']

                self.dict_polynoms[mode_id] = np.polyfit(lengths, frequencies, deg=1)
        
        else:
            for mode_id in mode_ids:
                fit_results = self.dict_results[mode_id]
                lengths = fit_results['length']
                frequencies = fit_results['f0']

                self.dict_polynoms[mode_id] = np.polyfit(lengths, frequencies, deg=1)
    
    def plot_data_results(self,
                          x: str,
                          y: str,
                          ax=None,
                          **kwargs):
        
        if ax is None:
            fig, ax = plt.subplots()
        
        for mode_id, dict_mode in self.dict_results.items():
            ax.scatter(dict_mode[x], dict_mode[y], label=mode_id, **kwargs)
        
        ax.set_xlabel(x)
        ax.set_ylabel(y)
    
    # def plot_data_results(self):
    #     """
    #     Plot fitted mode parameters as a function of cavity length and
    #     resonance frequency.

    #     The generated figure contains five panels:

    #     - Resonance frequency versus cavity length.
    #     - Coupling rate :math:`\\kappa_t` versus cavity length (log scale).
    #     - Coupling rate :math:`\\kappa_t` versus frequency (log scale).
    #     - Coupling rate :math:`\\kappa_t` versus cavity length (linear scale).
    #     - Coupling rate :math:`\\kappa_t` versus frequency (linear scale).

    #     Notes
    #     -----
    #     Coupling rates are displayed in MHz and are obtained from the
    #     fitted parameter ``kt``.
    #     """
    
    #     fig = plt.figure(figsize=(15, 9))
    #     gs = gridspec.GridSpec(2, 3)
        
    #     axl_freq = fig.add_subplot(gs[:, 0])
    #     axl_ktlog = fig.add_subplot(gs[0, 1])
    #     axf_ktlog = fig.add_subplot(gs[1, 1])
    #     axl_kt = fig.add_subplot(gs[0, 2])
    #     axf_kt = fig.add_subplot(gs[1, 2])

    #     fmin = self.data.isel(length=0, freq = self.data.freq.argmin('freq')).freq.values
    #     fmax = self.data.isel(length=0, freq = self.data.freq.argmax('freq')).freq.values
    #     lmin = self.data.isel(freq=0, length = self.data.length.argmin('length')).length.values
    #     lmax = self.data.isel(freq=0, length = self.data.length.argmax('length')).length.values
        
    #     for mode_id, dict_mode in self.dict_results.items():
    #         axl_freq.scatter(dict_mode['length'], dict_mode['f0'], label=f"{mode_id}", s=5)
    #         axl_ktlog.scatter(dict_mode['length'], np.array(dict_mode['kt'])*1e3, label=f"{mode_id}", s=5)
    #         axf_ktlog.scatter(dict_mode['f0'], np.array(dict_mode['kt'])*1e3, label=f"{mode_id}", s=5)
    #         axl_kt.scatter(dict_mode['length'], np.array(dict_mode['kt'])*1e3, label=f"{mode_id}", s=5)
    #         axf_kt.scatter(dict_mode['f0'], np.array(dict_mode['kt'])*1e3, label=f"{mode_id}", s=5)
        
    #     axl_freq.set_xlabel('Cavity length [mm]')
    #     axl_freq.set_ylabel('Frequency [GHz]')
    #     axl_freq.set_xlim(lmin, lmax)
    #     axl_freq.set_ylim(fmin, fmax)
    #     axl_freq.legend()
    #     axl_freq.grid(True)
        
    #     axl_ktlog.set_xlabel('Cavity length [mm]')
    #     axl_ktlog.set_ylabel('$\kappa_t$ [MHz]')
    #     axl_ktlog.set_yscale("log")
    #     axl_freq.set_xlim(lmin, lmax)
    #     axl_ktlog.grid(True)
        
    #     axf_ktlog.set_xlabel('Frequency [GHz]')
    #     axf_ktlog.set_ylabel('$\kappa_t$ [MHz]')
    #     axf_ktlog.set_yscale("log")
    #     axl_freq.set_xlim(fmin, fmax)
    #     axf_ktlog.grid(True)

    #     freq = self.data.freq.values
        
    #     axl_kt.set_xlabel('Cavity length [mm]')
    #     axl_kt.set_ylabel('$\kappa_t$ [MHz]')
    #     axl_freq.set_xlim(lmin, lmax)
    #     axl_kt.set_ylim(0, 5)
    #     axl_kt.grid(True)
        
    #     axf_kt.set_xlabel('Frequency [GHz]')
    #     axf_kt.set_ylabel('$\kappa_t$ [MHz]')
    #     axf_kt.set_xlim(np.min(freq), np.max(freq))
    #     axl_freq.set_xlim(fmin, fmax)
    #     axf_kt.set_ylim(0, 5)
    #     axf_kt.grid(True)
        
    #     fig.tight_layout()